export const vehicule = [
  {
    id: "1",
    // 
    make:"ZONSEN",
    prix:"Rs ",
    petrol:"4-Stroke, Petrol/Gasoline ",
    image: "7_seater_back.png",
    engineModel: "Euro Il Emission Standard Spark-Ignition, Single Cylinder, Liquid-Cotled",
    maximumOutput: "10.3 kW / 7500 rpm",
    MaximumTorque: "14.2 N-m / 6000 rpm",
    NumberofCylinder: "1",
    Displacement: "197cc",
    Bore: "63mm",
    Stroke: "63.5mm",
    CompressionRatio: "10.5 : 1",
    LubricationMethod: "Pressure and Splash",
    LubricantCapacity: "1.4 Liter (Max.)",
    StartingMethod: "Electric Start & Kick Start",
    SpeciChangeficFuelConsumption: "20-25Kms/Litre",
    OilVolume: "1.4 Litre",
    Coolingsystemfillingquantity : "3.5 L Water",
    Thermostat: "Thermostat with 83 C opening begin",

    Clutch : "Manual / Wet Multidisc (7-plates)",
    
    Transmission : "Constant Mesh, Two-stage Transmission; 6-Speed Gearshift (5-Forward + 1Reverse Gear",

    PropellerShaft: "Universal cross joint propeller shaft (20x17)",

    FrameType: "Fabricated / C-Section Steel Channels CRC 35x65x10-3.5mm",
    FrontSuspension : "Heavy Duty 2 Shock Absorbers, 2 Spring Cushion",
    RearSuspension : "2 Leaf Springs, 2 Shock Absorber",
    FuelTankCapacity: "6.5 Liters",
    FrontBrake: "Mechanical (Drum Type)",
    RearBrake: "Hydraulic (Disc Type)",
    TyreRimSize: "4.50-12 : 8 Ply Rating",
    TyresType : "Tube Type Rubber Tyres",
    TyresPressure : "58 PSI",
    OperatingVoltage : "12 V , Negative grounded",
    Battery: "12V-S50(34Ah)",
    Electronics:"Fan Light, FM Tape, Speaker, Ignition Switch, Motorized Wiper, High/Low Beam Indication Indicators Left Ri ht Head Li  h On Off Switch",

    InstrumentPanel:"Speedometer, Odometer, Temperature Meter, •RPM Meter",
    SeatingCapacity :" 6 - Seater",
    WheelBase :"2100 mm (82.7 inches)",
    WheelTrack1130 :"mm (44.5 inches)",
    OverallLength :"2970 mm (116.9 inches)",
    OverllWidth :" 1220 mm (48 inches)",
    OverallHeight :"1940 mm (76.4 inches)",
    WeightKgs :"450 Kg",
    Maximumdrivingspeed: "75 KPH",
    Gradeability: "16%",
    TurningCircle: "7950 mm (313 inches)",

  },
  {
    id: "2",
    Make: "ZONSEN",
    Petrol: "4-Stroke, Petrol/Gasoline Engine",
    EngineModel: "Euro Il Emission Standard",
    SparkIgnition: "SparkIgnition, Single Cylinder, Liquid-Cooled",
    MaximumOutput: "10.3 kW / 7500 rpm",
    MaximumTorque: "14.2 N-m / 6000 rpm",
    NumberofCylinder: "1",
    Displacement: "197cc",
    Bore: "63mm",
    Stroke: "63.5mm",
    CompressionRatio: "10.5 : 1",
    LubricationMethod: "Pressure and Splash",
    LubricantCapacity: "1.4 Liter (Max.)",
    StartingMethod: "Electric Start & Kick Start",
    SpecificFuelConsumption: "20-25Kms/Litre",
    OilChangeVolume: "1.4 Litre",
    Coolingsystemfillingquantity : "3.5 L Water",
    Thermostat : "Thermostat with 83 C opening begin",
    Clutch:"Manual / Wet Multidisc (7-plates)",
    Transmission : "Constant Mesh, Two-stage Transmission, 6-Speed Gearshift (5-Forward + 1Reverse Gear",
    PropellerShaft : "Universal cross joint propeller shaft (20x17)",
    FrameType: "Fabricated / Rectangular Pipe Steel CRC 40x80x2.5mm",
    FrontSuspension : "Heavy Duty 2 Shock Absorbers, 2 Spring Cushion",
    RearSuspension : "2 Leaf Springs, 2 Shock Absorber",
    FuelTankCapacity: "6.5 Liters",
    FrontBrake: "Mechanical (Drum Type)",
    RearBrake: "Hydraulic (Disc Type)",
    TyreRimSize: "4.50-12 : 8 Ply Rating",
    TyresType : "Tube Type Rubber Tyres",
    TyresPressure : "58 PSI",
    OperatingVoltage : "12 V , Negative grounded",
    Battery: "12V-S50(34Ah)",
    Electronics : "FanLight, FM Tape, Speaker, Ignition Switch, Motorized Wiper, High/Low Beam Indication Indicators Left Ri ht Head Li ht On Off Switch",
    InstrumentPanel : "Speedometer, Odometer, Temperature Meter, RPM Meter",

    SeatingCapacity:"9 - Seater",
    WheelBase:"2435 mm (95.9 inches)",
    WheelTrack:"1130 mm (44.5 inches)",
    OverallLength:"3305 mm (130.1 inches)",
    OverallWidth:"1220 mm (48 inches)",
    OverallHeight:"1940 mm (76.4 inches)",
    WeightKgs:"505.4 Kg",
    Maximumdrivingspeed: "75 KPH",
    Gradeability: "16%",
    TurningCircle: "8250 mm (324 inches)",
    image: "pickupfront01.png"

  },
  {

    id: "3",
    Make: "ZONSEN",
    Petrol: "4-Stroke, Petrol/Gasoline Engine",
    EngineModel: "4-Strock, Spark-Ignition, Single Cylinder, Liquid-Cooled",
    SparkIgnition: "SparkIgnition, Single Cylinder, Liquid-Cooled",
    MaximumOutput: "10.3 kW / 7500 rpm",
    MaximumTorque: "14.2 N-m / 6000 rpm",
    NumberofCylinder: "1",
    Displacement: "197cc",
    Bore: "63mm",
    Stroke: "63.5mm",
    CompressionRatio: "10.5 : 1",
    LubricationMethod: "Pressure and Splash",
    LubricantCapacity: "1.4 Liter (Max.)",
    StartingMethod: "Electric Start & Kick Start",
    SpecificFuelConsumption: "20-25Kms/Litre",
    OilChangeVolume: "1.4 Litre",
    Coolingsystemfillingquantity : "3.5 L Water",
    Thermostat : "Thermostat with 83 C opening begin",
    Clutch:"Manual / Wet Multidisc (7-plates)",
    Transmission : "Constant Mesh, Two-stage Transmission, 6-Speed Gearshift (5-Forward + 1Reverse Gear",
    PropellerShaft : "Universal cross joint propeller shaft (20x17)",
    FrameType: "Fabricated / Rectangular Pipe Steel CRC 40x80x2.5mm",
    FrontSuspension : "Heavy Duty 2 Shock Absorbers, 2 Spring Cushion",
    RearSuspension : "2 Leaf Springs, 2 Shock Absorber",
    FuelTankCapacity: "6.5 Liters",
    FrontBrake: "Mechanical (Drum Type)",
    RearBrake: "Hydraulic (Disc Type)",
    TyreRimSize: "4.50-12 : 8 Ply Rating",
    TyresType : "Tube Type Rubber Tyres",
    TyresPressure : "58 PSI",
    OperatingVoltage : "12 V , Negative grounded",
    Battery: "12V-S50(34Ah)",
    Electronics : "FanLight, FM Tape, Speaker, Ignition Switch, Motorized Wiper, High/Low Beam Indication Indicators Left Ri ht Head Li ht On Off Switch",
    InstrumentPanel : "Speedometer, Odometer, Temperature Meter, RPM Meter",

    SeatingCapacity:"9 - Seater",
    WheelBase:"2435 mm (95.9 inches)",
    WheelTrack:"1130 mm (44.5 inches)",
    OverallLength:"3305 mm (130.1 inches)",
    OverallWidth:"1220 mm (48 inches)",
    OverallHeight:"1940 mm (76.4 inches)",
    WeightKgs:"505.4 Kg",
    Maximumdrivingspeed: "75 KPH",
    Gradeability: "16%",
    TurningCircle: "8250 mm (324 inches)",
    image: "pickupfront01.png"

  },
  {
    id: "3",
    title: "",
    describe: "lorem html",
    image: "150cchighcabin_2.png",
  },
  {
    id: "4",
    title: "Seater",
    describe: "lorem html",
    image: "7_seater_back.png",
  },
  {
    id: "5",
    title: "Cargo",
    describe: "lorem html",
    image: "cargo01.png",
  },
  {
    id: "6",
    title: "Deca",
    describe: "lorem html",
    image: "deca_pm_front.png",
  },
  {
    id: "7",
    title: "Pick Up",
    describe: "lorem html",
    image: "pickupfront01.png",
  }
];
